export { default as ComprasPage } from "./pages/ComprasPage"
export { default as NuevaCompraPage } from "./pages/NuevaCompraPage"
export { default as DetalleCompraPage } from "./pages/DetalleCompraPage"
export { compraService } from "./services/compra.service"
export { useCompras } from "./hooks/useCompras"
export { useCompra } from "./hooks/useCompra"
export { createCompraSchema } from "./schemas/compra.schema"
export type { CreateCompraFormData } from "./schemas/compra.schema"
export type { Compra, DetalleCompra, CreateCompraInput, UpdateEstadoCompraInput } from "./types/compras.types"
