export { default as GastosPage } from "./pages/GastosPage"
export { default as NuevoGastoPage } from "./pages/NuevoGastoPage"
export { default as DetalleGastoPage } from "./pages/DetalleGastoPage"
export { gastoService } from "./services/gasto.service"
export { useGastos } from "./hooks/useGastos"
export { useGasto } from "./hooks/useGasto"
export { createGastoSchema, updateGastoSchema } from "./schemas/gasto.schema"
export type { CreateGastoFormData, UpdateGastoFormData } from "./schemas/gasto.schema"
export type { Gasto, CreateGastoInput, UpdateGastoInput } from "./types/gasto.types"
