export { default as TrabajadoresPage } from "./pages/TrabajadoresPage"
export { default as NuevoTrabajadorPage } from "./pages/NuevoTrabajadorPage"
export { default as DetalleTrabajadorPage } from "./pages/DetalleTrabajadorPage"
export { trabajadorService } from "./services/trabajador.service"
export { useTrabajadores } from "./hooks/useTrabajadores"
export { useTrabajador } from "./hooks/useTrabajador"
export { createTrabajadorSchema, updateTrabajadorSchema } from "./schemas/trabajador.schema"
export type { CreateTrabajadorFormData, UpdateTrabajadorFormData } from "./schemas/trabajador.schema"
export type { Trabajador, CreateTrabajadorInput, UpdateTrabajadorInput } from "./types/trabajador.types"
