export { default as InventarioPage } from "./pages/InventarioPage"
export { default as NuevoInventarioPage } from "./pages/NuevoInventarioPage"
export { default as DetalleInventariopage } from "./pages/DetalleInventariopage"
export { InventarioTable } from "./components/InventarioTable"
export { InventarioForm } from "./components/InventarioForm"
export type { InventarioFormProps } from "./components/InventarioForm"
export { InventarioCard } from "./components/InventarioCard"
export type { InventarioCardProps } from "./components/InventarioCard"
export { MovimientoForm } from "./components/MovimientoForm"
export type { MovimientoFormProps } from "./components/MovimientoForm"
export { inventarioService } from "./services/inventario.service"
export { useInventario } from "./hooks/useInventario"
export { useProducto } from "./hooks/useProducto"
export { createProductoSchema, updateProductoSchema, createMovimientoSchema } from "./schemas/inventario.schema"
export type { CreateProductoFormData, UpdateProductoFormData, CreateMovimientoFormData } from "./schemas/inventario.schema"
export type { Producto, CreateProductoInput, UpdateProductoInput, MovimientoInventario, CreateMovimientoInput } from "./types/inventario.types"
