export { default as ProduccionPage } from "./pages/ProduccionPage"
export { default as NuevaProduccionPage } from "./pages/NuevaProduccionPage"
export { default as DetalleProduccionPage } from "./pages/DetalleProduccionPage"
export { produccionService } from "./services/produccion.service"
export { useProducciones } from "./hooks/useProducciones"
export { useProduccion } from "./hooks/useProduccion"
export { createProduccionSchema, updateProduccionSchema } from "./schemas/produccion.schema"
export type { CreateProduccionFormData, UpdateProduccionFormData } from "./schemas/produccion.schema"
export type { Produccion, CreateProduccionInput, UpdateProduccionInput } from "./types/produccion.types"
