export { default as DashboardPage } from "./pages/DashboardPage"
export { StatsCard } from "./components/StatsCard"
export { ActivityList } from "./components/ActivityList"
export { SummaryChart } from "./components/SummaryChart"
export { StockAlert } from "./components/StockAlert"
export { QuickLinks } from "./components/QuickLinks"
export { useDashboard } from "./hooks/useDashboard"
export { dashboardService } from "./services/dashboard.service"
export type { DashboardData, DashboardStats, ActividadReciente, ProductoStockBajo, VentasResumen, GastosResumen } from "./types/dashboard.types"
