const BASE = "/api" as const

export const API_ENDPOINTS = {
  HEALTH: `${BASE}/health`,
  AUTH: {
    LOGIN: `${BASE}/auth/login`,
    REGISTER: `${BASE}/auth/register`,
    REFRESH: `${BASE}/auth/refresh`,
    ME: `${BASE}/auth/me`,
    FORGOT_PASSWORD: `${BASE}/auth/forgot-password`,
  },
  DASHBOARD: {
    RESUMEN: `${BASE}/dashboard/resumen`,
  },
  USERS: `${BASE}/users`,
  FINCAS: `${BASE}/fincas`,
  LOTES: `${BASE}/lotes`,
  CULTIVOS: `${BASE}/cultivos`,
  CLIENTES: `${BASE}/clientes`,
  PROVEEDORES: `${BASE}/proveedores`,
  PRODUCTOS: `${BASE}/productos`,
  MOVIMIENTOS: `${BASE}/movimientos`,
  VENTAS: `${BASE}/ventas`,
  GASTOS: `${BASE}/gastos`,
  TRABAJADORES: `${BASE}/trabajadores`,
  JORNALES: `${BASE}/jornales`,
  BITACORA: `${BASE}/bitacora`,
  ROLES: `${BASE}/roles`,
  PERMISOS: `${BASE}/permisos`,
  AUDITORIA: `${BASE}/auditoria`,
  TEMPORADAS: `${BASE}/temporadas`,
  PRODUCCION: `${BASE}/produccion`,
  RENDIMIENTO_LOTES: `${BASE}/rendimiento/lotes`,
  RENDIMIENTO_CULTIVOS: `${BASE}/rendimiento/cultivos`,
  CATEGORIAS: `${BASE}/categorias`,
  COMPRAS: `${BASE}/compras`,
  AJUSTES: `${BASE}/ajustes`,
  ALERTAS: `${BASE}/alertas`,
  HISTORIAL_LABORAL: `${BASE}/historial-laboral`,
  ASISTENCIAS: `${BASE}/asistencias`,
  ACTIVIDADES_ASIGNADAS: `${BASE}/actividades-asignadas`,
  CALENDARIO: `${BASE}/calendario`,
  RECORDATORIOS: `${BASE}/recordatorios`,
  ACTIVIDADES: `${BASE}/actividades`,
  CAJA: `${BASE}/caja`,
  MOVIMIENTOS_CAJA: `${BASE}/caja/movimientos`,
  FLUJO: `${BASE}/flujo`,
  PRESUPUESTOS: `${BASE}/presupuestos`,
  NOTIFICACIONES: `${BASE}/notificaciones`,
  CONFIGURACION: `${BASE}/configuracion`,
} as const

export const API_TIMEOUT = 15000
