export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/app/dashboard",
  FINCAS: "/app/fincas",
  FINCA_NUEVA: "/app/fincas/nueva",
  FINCA_DETALLE: (id: number | string) => `/app/fincas/${id}`,
  LOTES: "/app/lotes",
  LOTE_NUEVO: "/app/lotes/nuevo",
  LOTE_DETALLE: (id: number | string) => `/app/lotes/${id}`,
  INVENTARIO: "/app/inventario",
  INVENTARIO_NUEVO: "/app/inventario/nuevo",
  INVENTARIO_DETALLE: (id: number | string) => `/app/inventario/${id}`,
  BITACORA: "/app/bitacora",
  BITACORA_NUEVA: "/app/bitacora/nueva",
  BITACORA_DETALLE: (id: number | string) => `/app/bitacora/${id}`,
  FINANZAS: "/app/finanzas",
  FINANZAS_NUEVO: "/app/finanzas/nuevo",
  FINANZAS_DETALLE: (id: number | string) => `/app/finanzas/${id}`,
  REPORTES: "/app/reportes",
  REPORTE_NUEVO: "/app/reportes/nuevo",
  REPORTE_DETALLE: (id: number | string) => `/app/reportes/${id}`,
  PERFIL: "/app/perfil",
  CONFIGURACION: "/app/configuracion",
} as const
