export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  RECUPERAR_PASSWORD: "/recuperar-password",
  DASHBOARD: "/app/dashboard",
  FINCAS: "/app/fincas",
  FINCA_NUEVA: "/app/fincas/nueva",
  FINCA_DETALLE: (id: number | string) => `/app/fincas/${id}`,
  LOTES: "/app/lotes",
  LOTE_NUEVO: "/app/lotes/nuevo",
  LOTE_DETALLE: (id: number | string) => `/app/lotes/${id}`,
  CULTIVOS: "/app/cultivos",
  CULTIVO_NUEVO: "/app/cultivos/nuevo",
  CULTIVO_DETALLE: (id: number | string) => `/app/cultivos/${id}`,
  INVENTARIO: "/app/inventario",
  INVENTARIO_NUEVO: "/app/inventario/nuevo",
  INVENTARIO_DETALLE: (id: number | string) => `/app/inventario/${id}`,
  MOVIMIENTOS: "/app/movimientos",
  MOVIMIENTO_NUEVO: "/app/movimientos/nuevo",
  MOVIMIENTO_DETALLE: (id: number | string) => `/app/movimientos/${id}`,
  BITACORA: "/app/bitacora",
  BITACORA_NUEVA: "/app/bitacora/nueva",
  BITACORA_DETALLE: (id: number | string) => `/app/bitacora/${id}`,
  TRABAJADORES: "/app/trabajadores",
  TRABAJADOR_NUEVO: "/app/trabajadores/nuevo",
  TRABAJADOR_DETALLE: (id: number | string) => `/app/trabajadores/${id}`,
  JORNALES: "/app/jornales",
  JORNAL_NUEVO: "/app/jornales/nuevo",
  JORNAL_DETALLE: (id: number | string) => `/app/jornales/${id}`,
  VENTAS: "/app/ventas",
  VENTA_NUEVA: "/app/ventas/nuevo",
  VENTA_DETALLE: (id: number | string) => `/app/ventas/${id}`,
  GASTOS: "/app/gastos",
  GASTO_NUEVO: "/app/gastos/nuevo",
  GASTO_DETALLE: (id: number | string) => `/app/gastos/${id}`,
  FINANZAS: "/app/finanzas",
  FINANZAS_NUEVO: "/app/finanzas/nuevo",
  FINANZAS_DETALLE: (id: number | string) => `/app/finanzas/${id}`,
  REPORTES: "/app/reportes",
  REPORTE_NUEVO: "/app/reportes/nuevo",
  REPORTE_DETALLE: (id: number | string) => `/app/reportes/${id}`,
  PERFIL: "/app/perfil",
  CONFIGURACION: "/app/configuracion",
} as const
