export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  RECUPERAR_PASSWORD: "/recuperar-password",
  DASHBOARD: "/app/dashboard",
  FINCAS: "/app/fincas",
  FINCA_NUEVA: "/app/fincas/nueva",
  FINCA_DETALLE: (id: number | string) => `/app/fincas/${id}`,
  LOTES: "/app/lotes",
  LOTE_NUEVO: "/app/lotes/nuevo",
  LOTE_DETALLE: (id: number | string) => `/app/lotes/${id}`,
  CULTIVOS: "/app/cultivos",
  CULTIVO_NUEVO: "/app/cultivos/nuevo",
  CULTIVO_DETALLE: (id: number | string) => `/app/cultivos/${id}`,
  INVENTARIO: "/app/inventario",
  INVENTARIO_NUEVO: "/app/inventario/nuevo",
  INVENTARIO_DETALLE: (id: number | string) => `/app/inventario/${id}`,
  MOVIMIENTOS: "/app/movimientos",
  MOVIMIENTO_NUEVO: "/app/movimientos/nuevo",
  MOVIMIENTO_DETALLE: (id: number | string) => `/app/movimientos/${id}`,
  BITACORA: "/app/bitacora",
  BITACORA_NUEVA: "/app/bitacora/nueva",
  BITACORA_DETALLE: (id: number | string) => `/app/bitacora/${id}`,
  TRABAJADORES: "/app/trabajadores",
  TRABAJADOR_NUEVO: "/app/trabajadores/nuevo",
  TRABAJADOR_DETALLE: (id: number | string) => `/app/trabajadores/${id}`,
  JORNALES: "/app/jornales",
  JORNAL_NUEVO: "/app/jornales/nuevo",
  JORNAL_DETALLE: (id: number | string) => `/app/jornales/${id}`,
  VENTAS: "/app/ventas",
  VENTA_NUEVA: "/app/ventas/nuevo",
  VENTA_DETALLE: (id: number | string) => `/app/ventas/${id}`,
  GASTOS: "/app/gastos",
  GASTO_NUEVO: "/app/gastos/nuevo",
  GASTO_DETALLE: (id: number | string) => `/app/gastos/${id}`,
  FINANZAS: "/app/finanzas",
  FINANZAS_NUEVO: "/app/finanzas/nuevo",
  FINANZAS_DETALLE: (id: number | string) => `/app/finanzas/${id}`,
  REPORTES: "/app/reportes",
  REPORTE_NUEVO: "/app/reportes/nuevo",
  REPORTE_DETALLE: (id: number | string) => `/app/reportes/${id}`,
  PERFIL: "/app/perfil",
  CONFIGURACION: "/app/configuracion",
  USUARIOS: "/app/usuarios",
  USUARIO_NUEVO: "/app/usuarios/nuevo",
  USUARIO_EDITAR: (id: number) => `/app/usuarios/${id}/editar`,
  USUARIO_DETALLE: (id: number) => `/app/usuarios/${id}`,
  ROLES: "/app/roles",
  ROL_NUEVO: "/app/roles/nuevo",
  ROL_EDITAR: (id: number) => `/app/roles/${id}/editar`,
  PERMISOS: "/app/permisos",
  PERMISO_NUEVO: "/app/permisos/nuevo",
  PERMISO_EDITAR: (id: number) => `/app/permisos/${id}/editar`,
  AUDITORIA: "/app/auditoria",
  TEMPORADAS: "/app/temporadas",
  TEMPORADA_NUEVA: "/app/temporadas/nueva",
  TEMPORADA_DETALLE: (id: number | string) => `/app/temporadas/${id}`,
  PRODUCCION: "/app/produccion",
  PRODUCCION_NUEVO: "/app/produccion/nuevo",
  PRODUCCION_DETALLE: (id: number | string) => `/app/produccion/${id}`,
  RENDIMIENTO: "/app/rendimiento",
  CATEGORIAS: "/app/categorias",
  CATEGORIA_NUEVA: "/app/categorias/nueva",
  CATEGORIA_DETALLE: (id: number | string) => `/app/categorias/${id}`,
  COMPRAS: "/app/compras",
  COMPRA_NUEVA: "/app/compras/nueva",
  COMPRA_DETALLE: (id: number | string) => `/app/compras/${id}`,
  AJUSTES: "/app/ajustes",
  AJUSTE_NUEVO: "/app/ajustes/nuevo",
  ALERTAS: "/app/alertas",
  HISTORIAL_LABORAL: "/app/historial-laboral",
  ASISTENCIAS: "/app/asistencias",
  ACTIVIDADES_ASIGNADAS: "/app/actividades-asignadas",
  CALENDARIO: "/app/calendario",
  ACTIVIDADES: "/app/actividades",
  ACTIVIDAD_NUEVA: "/app/actividades/nueva",
  ACTIVIDAD_DETALLE: (id: number | string) => `/app/actividades/${id}`,
  CAJA: "/app/caja",
  CAJA_NUEVA: "/app/caja/nueva",
  CAJA_DETALLE: (id: number | string) => `/app/caja/${id}`,
  FLUJO: "/app/flujo",
  PRESUPUESTOS: "/app/presupuestos",
  PRESUPUESTO_NUEVO: "/app/presupuestos/nuevo",
  PRESUPUESTO_DETALLE: (id: number | string) => `/app/presupuestos/${id}`,
  NOTIFICACIONES: "/app/notificaciones",
} as const
