export { default as CalendarioPage } from "./pages/CalendarioPage"
export { default as NuevoEventoPage } from "./pages/NuevoEventoPage"
export { default as DetalleEventoPage } from "./pages/DetalleEventoPage"
export { default as EditarEventoPage } from "./pages/EditarEventoPage"
export { calendarioService } from "./services/calendario.service"
export { recordatorioService } from "./services/recordatorio.service"
export { useEventosCalendario } from "./hooks/useEventosCalendario"
export { useEventoCalendario } from "./hooks/useEventoCalendario"
export { createEventoSchema, updateEventoSchema, createRecordatorioSchema } from "./schemas/calendario.schema"
export type { CreateEventoFormData, UpdateEventoFormData, CreateRecordatorioFormData } from "./schemas/calendario.schema"
export type { EventoCalendario, Recordatorio, CreateEventoInput, UpdateEventoInput, CreateRecordatorioInput } from "./types/calendario.types"
export { TIPO_EVENTO_OPTIONS, PRIORIDAD_OPTIONS } from "./types/calendario.types"
