export { default as VentasPage } from "./pages/VentasPage"
export { default as NuevaVentaPage } from "./pages/NuevaVentaPage"
export { default as DetalleVentaPage } from "./pages/DetalleVentaPage"
export { ventaService } from "./services/venta.service"
export { useVentas } from "./hooks/useVentas"
export { useVenta } from "./hooks/useVenta"
export { createVentaSchema, updateVentaSchema } from "./schemas/venta.schema"
export type { CreateVentaFormData, UpdateVentaFormData } from "./schemas/venta.schema"
export type { Venta, CreateVentaInput, UpdateVentaInput } from "./types/venta.types"
