export { default as BitacoraPage } from "./pages/BitacoraPage"
export { default as NuevaBitacoraPage } from "./pages/NuevaBitacoraPage"
export { default as DetalleBitacoraPage } from "./pages/DetalleBitacoraPage"
export { BitacoraTable } from "./components/bitacoraTable"
export { BitacoraForm } from "./components/BitacoraForm"
export type { BitacoraFormProps } from "./components/BitacoraForm"
export { BitacoraCard } from "./components/BitacoraCard"
export type { BitacoraCardProps } from "./components/BitacoraCard"
export { bitacoraService } from "./services/bitacora.service"
export { useBitacora } from "./hooks/useBitacora"
export { useBitacoraEntry } from "./hooks/useBitacoraEntry"
export { createBitacoraSchema, updateBitacoraSchema, ACTIVIDAD_OPTIONS } from "./schemas/bitacora.schema"
export type { CreateBitacoraFormData, UpdateBitacoraFormData } from "./schemas/bitacora.schema"
export type { Bitacora, CreateBitacoraInput, UpdateBitacoraInput, BitacoraFilters } from "./types/bitacora.types"
