export { default as CategoriasPage } from "./pages/CategoriasPage"
export { default as NuevaCategoriaPage } from "./pages/NuevaCategoriaPage"
export { default as DetalleCategoriaPage } from "./pages/DetalleCategoriaPage"
export { categoriaService } from "./services/categoria.service"
export { useCategorias } from "./hooks/useCategorias"
export { useCategoria } from "./hooks/useCategoria"
export { createCategoriaSchema, updateCategoriaSchema } from "./schemas/categoria.schema"
export type { CreateCategoriaFormData, UpdateCategoriaFormData } from "./schemas/categoria.schema"
export type { CategoriaProducto, CreateCategoriaInput, UpdateCategoriaInput } from "./types/categoria.types"
