export { default as ActividadesPage } from "./pages/ActividadesPage"
export { default as NuevaActividadPage } from "./pages/NuevaActividadPage"
export { default as DetalleActividadPage } from "./pages/DetalleActividadPage"
export { default as EditarActividadPage } from "./pages/EditarActividadPage"
export { actividadService } from "./services/actividades.service"
export { useActividades } from "./hooks/useActividades"
export { useActividad } from "./hooks/useActividad"
export { createActividadSchema, updateActividadSchema } from "./schemas/actividades.schema"
export type { CreateActividadFormData, UpdateActividadFormData } from "./schemas/actividades.schema"
export type { ActividadSeguimiento, Evidencia, ActividadProducto, CreateActividadInput, UpdateActividadInput } from "./types/actividades.types"
export { ESTADO_ACTIVIDAD_OPTIONS } from "./types/actividades.types"
